config/routes.rb
Wyszukiwarka::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :edit, :update]
  resources :books
  root 'home#index'
  resources :rent_cards, except: [:show, :index, :new, :edit] do 
    patch "return_books"
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, :author, :publishing_date, :isbn, presence: true
  has_many :rent_cards
  has_many :users, through: :rent_cards
  
  def self.browse(query)
    self.where("title REGEXP :query OR author REGEXP :query OR publishing_date REGEXP :query OR isbn REGEXP :query", query: query) 
  end  
  
  def available?
    self.amount > 0 
  end
end

app/models/rent_card.rb
class RentCard < ActiveRecord::Base
  belongs_to :user
  belongs_to :book      
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable,
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable
  
  has_many :rent_cards
  has_many :books, through: :rent_cards
  
  def has_book?(book)
    books.include?(book)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized
  
  private
  
  def not_authorized
    respond_to do |format|
      if user_signed_in?
        format.html { redirect_to root_path, notice: "You have no permission to do this task" }
      else
        format.html { redirect_to new_user_session_path, notice: "You have to log in first"}
      end  
    end  
  end  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  
  def index
    @rent_cards = current_user.rent_cards
    authorize current_user.books
  end
  
  def show
    @rent_card = RentCard.where(user_id: current_user.id, book_id: @book.id).first_or_initialize
    authorize @book
  end
  
  def new
    @book = Book.new
    authorize @book
  end
  
  def create
    @book = Book.new(book_params)
    authorize @book
    
    respond_to do |format|
      if @book.save
        format.html {redirect_to root_path}
      else
        format.html {redirect_to root_path, notice: "You gave incorrect data"}
      end  
    end      
  end   
  
  def edit
    authorize @book
  end
  
  def update
    authorize @book
    respond_to do |format|
      if @book.update_attributes(book_params)
        format.html { redirect_to @book, notice: "#{@book.title} successfully updated" }
      else
        format.html { render action: "edit", notice: "Something went wrong:(" }
      end
    end      
  end
  
  def destroy
    authorize @book
    @book.destroy!
    redirect_to root_path, notice: "Book deleted"
  end
  
  private
  
  def book_params
    params.require(:book).permit(:isbn, :title, :author, :publishing_date, :amount)
  end  
  
  def set_book
    @book = Book.find(params[:id])
  end
end  

app/controllers/concerns/rent_builder.rb
class RentBuilder
  attr_accessor :status, :rent_card
  
  def initialize(user, params)
    @book = Book.find(params[:book_id])
    @user = user
    @amount = params[:amount].to_i
    @rent_card = RentCard.where(user_id: @user.id, book_id: @book.id).first_or_initialize
    set_rent_card_amount
  end
  
  def rent_books
    unless @book.amount < @amount || @amount == 0
      @book.amount-= @amount
      @rent_card.amount += @amount
      @status = "You have successfully rented #{@book.title}!"
      @correct = true
    else  
      @status = "You can't rent this amount of books"
      @correct = false
    end  
  end
  
  def return_books
    if @amount > @rent_card.amount || @amount == 0
      @status = "Seems like you want to return books you don't have"
      @correct = false
    else  
      @status = "Thank you for returning the books"
      @book.amount+= @amount
      @rent_card.amount-= @amount
      check_rent_card
      @correct = true
    end  
  end
  
  def save!
    if @correct
      @book.save!
      if rent_card_destroyed?
        true
      else
        @rent_card.save!
      end  
    else
      false
    end    
  end
  
  private
  
  def check_rent_card
    if @rent_card.amount == 0
      @rent_card.destroy!
      @rent_card_destroyed = true
    end  
  end
  
  def set_rent_card_amount
    if @rent_card.amount.nil?
      @rent_card.amount = 0
    end  
  end
  
  def rent_card_destroyed?
    @rent_card_destroyed
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.browse(params[:search])
    
    respond_to do |format|
      format.html
      format.json { render json: @books }
    end
  end  
end  

app/controllers/rent_cards_controller.rb
class RentCardsController < ApplicationController
  before_action :set_book
  
  def create
    @rent_builder = RentBuilder.new(current_user, rent_card_params)
    @rent_builder.rent_books
    authorize @rent_builder.rent_card
    
    respond_to do |format|
      if @rent_builder.save!
        format.html { redirect_to @book, notice: @rent_builder.status }
      else
        format.html { redirect_to @book, notice: @rent_builder.status}  
      end
    end    
  end
  
  def update
    @rent_builder = RentBuilder.new(current_user, rent_card_params)
    @rent_builder.rent_books
    authorize @rent_builder.rent_card
    
    respond_to do |format|
      if @rent_builder.save!
        format.html { redirect_to @book, notice: @rent_builder.status}
      else
        format.html { redirect_to @book, notice: @rent_builder.status}  
      end
    end 
  end
  
  def return_books
    @rent_builder = RentBuilder.new(current_user, rent_card_params)
    authorize @rent_builder.rent_card
    @rent_builder.return_books
    
    respond_to do |format|
      if @rent_builder.save!
        format.html { redirect_to @book, notice: @rent_builder.status}
      else
        format.html { redirect_to @book, notice: @rent_builder.status}  
      end
    end  
  end
  
  private
  
  def set_book
    @book = Book.find(rent_card_params[:book_id])
  end 
  
  def rent_card_params
    params.require(:rent_card).permit(:user_id, :book_id, :amount)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  
  def index 
    @users = User.all
    authorize @users
  end
  
  def edit
    authorize @user
  end
  
  def update
    authorize @user
    respond_to do |format|
      if @user.update_attributes!(user_params)
        format.html { redirect_to :users, notice: "Users account updated" }
      else
        format.html { render action: "edit", notice: "Users account update failed"}
      end
    end      
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_admin_links.html.haml
%p
	= link_to "Edit book", edit_book_path(@book) if policy(Book).edit?
	= link_to "Delete book", book_path(@book), method: :delete if policy(Book).destroy?

app/views/books/_form.html.haml
= simple_form_for @book do |f|
	= f.input :title, label: false, placeholder: "title"
	= f.input :author, label: false, placeholder: "author"
	= f.input :isbn, label: false, placeholder: "ISBN"
	= f.input :publishing_date, label: false, placeholder: "Publishing date"
	= f.input :amount, label: false, placeholder: "Amount"
	= f.submit class: "btn btn-success"

app/views/books/_rent_form.html.haml
%h3= "Rent books"
= simple_form_for @rent_card, url: @rent_card.new_record? ? rent_cards_path : rent_card_path(@rent_card), method: @rent_card.new_record? ? :post : :patch do |f|
	= f.input :amount, label: false, placeholder: "How many copies?"
	= f.input :book_id, input_html: { value: @book.id }, as: :hidden
	= f.submit "Rent"

app/views/books/_return_form.html.haml
%h3= "Return books"
= simple_form_for @rent_card, url: rent_card_return_books_path(@rent_card), method: :patch do |f|
	= f.input :amount, label: false, placeholder: "How many copies?"
	= f.input :book_id, input_html: { value: @book.id }, as: :hidden
	= f.submit "Return"

app/views/books/edit.html.haml
%h1= "Edit #{@book.title}"

= render "form"

app/views/books/index.html.haml
%h1= "My books"

%table.table.table-striped
	%th Title
	%th How many you have
	- @rent_cards.each do |rent_card|
		%tr
			%td= link_to rent_card.book.title, book_path(rent_card.book)
			%td= rent_card.amount

app/views/books/new.html.haml
%h1= "Add new book"

= render "form"

app/views/books/show.html.haml
%h1= "#{@book.title}"
= render "admin_links"

%p= "Author: #{@book.author}"
%p= "ISBN: #{@book.isbn}"
%p= "Publishing date: #{@book.publishing_date}"
%p= "Amount: #{@book.amount}"

- if @book.available?
	= render "rent_form"
- else
	%p= "This book is unavailable for rent" 
	
- if current_user.has_book?(@book)	
	= render "return_form"
- else
	= nil

app/views/home/index.html.haml
= simple_form_for String.new, url: root_path, method: :get, html: { autocomplete: 'off' } do |f|
	= f.input_field :search, label: false, data: {role: "search-input"}, placeholder: "Search"
	
%table.table.table-striped
	%th Title
	%th Author
	%th ISBN number
	%th Publishing date
	%th Amount
.comment-box	

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Wyszukiwarka
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .main-page-container
      = link_to "Home", root_path		
      - if user_signed_in?
        %p
          = current_user.email
          = link_to "Log out", destroy_user_session_path, method: :delete
          = link_to "My books", books_path
          = link_to "Add new book", new_book_path if policy(Book).new?
          = link_to "Users", users_path if policy(User).index?
      - else
        %p
          = link_to "Log in", new_user_session_path
          = link_to "Sign up", new_user_registration_path  								
      - flash.each do |name, msg|
        .alert
          %button.close{"data-dismiss" => "alert", :type => "button"} &times;
          %p= msg				
      = yield

app/views/users/_form.html.haml
= simple_form_for @user do |f|
	= f.input :admin, as: :boolean, label: "Admin"
	= f.submit "Save"

app/views/users/edit.html.haml
%h1= "Edit user"
= render "form"

app/views/users/index.html.haml
%h1= "Users"

%table.table.table-striped
	%th= "ID"
	%th= "Email"
	- @users.each do |user|
		%tr
			%td= user.id
			%td= link_to user.email, edit_user_path(user)